apiVersion: v1
kind: Secret

metadata:
  name: grafana-secret
  namespace: request-system

type: Opaque

stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin

  # SMTP Configuration
  GF_SMTP_ENABLED: "true"
  GF_SMTP_HOST: smtp.gmail.com:587
  GF_SMTP_USER: shakthivelk1124@gmail.com
  GF_SMTP_PASSWORD: kiabzkhffhvwdusy
  GF_SMTP_FROM_ADDRESS: shakthivelk1124@gmail.com
  GF_SMTP_FROM_NAME: Grafana
  GF_SMTP_SKIP_VERIFY: "true"